#!/bin/sh


################################################################################
################################################################################
###	Program Name:			Sleep On Low Power		     ###
###	File:				solp				     ###
###	Author:				Samual G Brown			     ###
###	Date of Creation:		31/10/2020			     ###
###	Late Modified:			31/10/2020			     ###
###	Purpos:				To warn the user when the machines   ###
###					batter level is below some certain   ###
###					percentage and to put the machine    ###
###					to sleep if the machines batter      ###
###					level is below some certain	     ###
###					percentage independent of the	     ###
###					previously mentioned percentage.     ###
###	Description of prog operation:
################################################################################
################################################################################


################################# Program paths ################################
################################################################################
SYSCTL_PROG="/sbin/sysctl"
ZENITY_PROG="/usr/local/bin/zenity"
ECHO_PROG="/bin/echo"
BC_PROG="/usr/bin/bc"
SLEEP_PROG="/bin/sleep"
TOUCH_PROG="/usr/bin/touch"
RM_PROG="/bin/rm"


################################### Constants ##################################
################################################################################
TRUE="1"
FALSE="0"
WARNING_THRESHOLD="12"
SLEEP_THRESHOLD="7"
CURRENT_CARGING_STATUS=`${SYSCTL_PROG} -n hw.acpi.acline`
CARGING_OFF="0"			# 1 if machine is charging 0 if not.
BATTERY_LEVEL=`${SYSCTL_PROG} -n hw.acpi.battery.life`


displayWarningMessage()
{	# The following arguments should be passed "window title" and
    # "warning message"
    $ZENITY_PROG --warning --title "${1}" --width 300 --text \
		 "${2}"
}


cowntdown()
{	# The following arguments should be passed "sleep interval",
    # "sleep message" and "window title" their order should be as seen here.
    # Where sleep interval is the time spent sleeping between status bar updates
    # (for example if sleep interval was 0.6 then the status bar would take one
    # minute to complete as 0.6*100 = 60).
    local STATUS_BAR_MIN="0"
    local STATUS_BAR_MAX="100"
    
    (for iter in $(seq $STATUS_BAR_MIN $STATUS_BAR_MAX)
     do
	 local timeLeft=`$ECHO_PROG "( ${STATUS_BAR_MAX} - ${iter} ) * \
${1}" | $BC_PROG`;

	 # Check charging status and return if charging.
	 if [ `${SYSCTL_PROG} -n hw.acpi.acline` -ne $CARGING_OFF ]
	 then			# We are now charging
	     break
	 fi
	 
	 $ECHO_PROG "${2}${timeLeft}s"
	 $ECHO_PROG "${iter}"
	 $SLEEP_PROG "${1}"
     done) | zenity --progress --title "${3}" --auto-close --no-cancel

    # Reset CURRENT_CARGING_STATUS as it may have changed. This should be
    # checked for after this function is run.
    CURRENT_CARGING_STATUS=`${SYSCTL_PROG} -n hw.acpi.acline`
}


zzzSleep()
{	# Lock the computer and put it to sleep.
    #    /home/magenta/.config/i3/configdir/lock.sh
    echo sleeping
}


setDialogueDisplayed()
{	# The following arguments should be passed
    # "dialogue displayed info dir" and "dialogue threshold", where dialogue
    # displayed info dir is the directory of the sentinal file that will
    # indicate wheather or not a dialogue box should possibly be displayed, and
    # dialogue threshold is the battery level at which the dialouge should be
    # displayed.
    if [ $BATTERY_LEVEL -le $2 ]
    then			# If the battery level is less than.
	if [ \( ! -f "${1}" \) -a \( $CURRENT_CARGING_STATUS -eq $CARGING_OFF \) ]
	then			# If the file doesn't exist create it.
	    echo "File Created ${1}"
	    $TOUCH_PROG $1
	fi
    else			# If the battery level is greater than.
	if [ \( -f "${1}" \) -o \( $CURRENT_CARGING_STATUS -ne $CARGING_OFF \) ]
	then			# If it does exist remove it.
	    echo "File removed ${1}"
	    $RM_PROG $1
	fi
    fi
}


dialogueDisplayed()
{	# The following arguments should be passed
    # "dialogue displayed info dir", where dialogue displayed info dir is the
    # directory of the sentinal file that will indicate wheather or not a
    # dialogue box should possibly be displayed.
    if [ -f "${1}" ]
    then
	RET=$TRUE
#	echo "file exists"
    else
	RET=$FALSE
#	echo "file doesn't exist"
    fi
    $ECHO_PROG $RET
}


handel()
{
    local SLEEP_DIALOGUE_DISPLAYED_INFO_DIR="/tmp/sleepDialogueDisplayed"
    local WARNING_DIALOGUE_DISPLAYED_INFO_DIR="/tmp/sleepWarningDialogueDisplayed"
    
    if [ $CURRENT_CARGING_STATUS -eq $CARGING_OFF ]
    then			# We are on battery power.
	if [ \( $BATTERY_LEVEL -le $SLEEP_THRESHOLD \) -a \( `dialogueDisplayed "${SLEEP_DIALOGUE_DISPLAYED_INFO_DIR}"` -eq $FALSE \) ]
	then			# The battery level is below $SLEEP_THRESHOLD.
	    local SLEEP_INTERVAL="0.6"
	    local SLEEP_MESSAGE="# Battery at or below (${BATTERY_LEVEL}%). \
Computer will sleep in "
	    local WINDOW_TITLE="WARNING LOW BATTERY (${BATTERY_LEVEL}%)"
	    
	    cowntdown "${SLEEP_INTERVAL}" "${SLEEP_MESSAGE}" "${WINDOW_TITLE}"
	    if [ $CURRENT_CARGING_STATUS -eq $CARGING_OFF ]
	    then		# We are still not charging.
		zzzSleep
	    fi
	else
	    if [ \( $BATTERY_LEVEL -le $WARNING_THRESHOLD \) -a \( `dialogueDisplayed "${WARNING_DIALOGUE_DISPLAYED_INFO_DIR}"` -eq $FALSE \) ]
	    then		# The battery level is above $SLEEP_THRESHOLD
		# but below $WARNING_THRESHOLD.
		local WINDOW_TITLE="Warning Low Battery (${BATTERY_LEVEL}%)"
		local WARNING_MESSAGE="It has been detected that your machines \
batterry level is ${BATTERY_LEVEL}% which is at or below ${WARNING_THRESHOLD}%!\
 The machine will automatically be put to sleep when it is detected that the \
battery level is at or below ${SLEEP_THRESHOLD}%!"

	    	displayWarningMessage "${WINDOW_TITLE}" "${WARNING_MESSAGE}"
	    fi
	fi
    fi

    # Recorde whether or to dialogues have already been displayed since entering
    # the relevant battery percentages.
    setDialogueDisplayed $SLEEP_DIALOGUE_DISPLAYED_INFO_DIR $SLEEP_THRESHOLD
    setDialogueDisplayed $WARNING_DIALOGUE_DISPLAYED_INFO_DIR $WARNING_THRESHOLD
}


main()
{
    BATTERY_LEVEL="8"

    handel
}


main
